services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpenDxp\Model\Version\Adapter\VersionStorageAdapterInterface:
        public: true
        alias: OpenDxp\Model\Version\Adapter\ProxyVersionStorageAdapter

    OpenDxp\Model\Version\Adapter\ProxyVersionStorageAdapter: ~
