<?php
declare(strict_types=1);

/**
 * OpenDXP
 *
 * This source file is licensed under the GNU General Public License version 3 (GPLv3).
 *
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 * @copyright  Copyright (c) Pimcore GmbH (https://pimcore.com)
 * @copyright  Modification Copyright (c) OpenDXP (https://www.opendxp.ch)
 * @license    https://www.gnu.org/licenses/gpl-3.0.html  GNU General Public License version 3 (GPLv3)
 */

namespace OpenDxp\Routing\Loader;

use Override;
use ReflectionClass;
use ReflectionMethod;
use Symfony\Bundle\FrameworkBundle\Routing\AttributeRouteControllerLoader as BaseAttributeRouteControllerLoader;

/**
 * Normalizes autogenerated admin routes to opendxp_admin_
 *
 * @internal
 */
class AttributeRouteControllerLoader extends BaseAttributeRouteControllerLoader
{
    #[Override]
    protected function getDefaultRouteName(ReflectionClass $class, ReflectionMethod $method): string
    {
        $routeName = parent::getDefaultRouteName($class, $method);

        $replacements = [
            'opendxp_admin_admin_' => 'opendxp_admin_',
        ];

        return str_replace(
            array_keys($replacements),
            array_values($replacements),
            $routeName
        );
    }
}
