services:
    _defaults:
        autowire: true
        autoconfigure: true

    # redirect handler used to handle redirects before/after routing
    OpenDxp\Bundle\SeoBundle\Redirect\RedirectHandler: ~

    OpenDxp\Bundle\SeoBundle\Redirect\RedirectTableProvider: ~

    OpenDxp\Bundle\SeoBundle\Redirect\RedirectHitCounter: ~

    #
    # REDIRECTS Export
    #

    OpenDxp\Bundle\SeoBundle\Redirect\Csv: ~