name: Improvement
description: Request or propose an improvement
title: "[Improvement]: "
labels: [ Improvement ]
body:
    -   type: markdown
        attributes:
            value: |
                ## Before Suggesting an Improvement
                We're grateful for community contributions — your ideas help shape and grow this project.  
                That said, **we're not building features on demand for individuals or companies**.  
                We’re excited to collaborate on ideas that make the project better for everyone.
        
                For larger or more general ideas, please [start a discussion](https://github.com/open-dxp/opendxp/discussions) first. This helps clarify the scope and avoid unnecessary effort.
        
                Once your idea is clearly defined, feel free to open an issue — or better yet, submit a pull request (PR). We're always happy to review and potentially merge well-prepared contributions.
        
                Feature suggestions that don't meet the following requirements may be closed or deleted without further notice:
                - There is no existing issue already addressing the same topic  
                - The request is clear, specific, and ready to be worked on
    -   type: textarea
        attributes:
            label: Improvement description
        validations:
            required: true
