services:
    _defaults:
        autowire: true
        autoconfigure: true

    opendxp.class.resolver.document:
        public: true
        class: OpenDxp\Resolver\ClassResolver
        arguments:
            $map: '%opendxp.documents.classes.map%'

    opendxp.class.resolver.asset:
        public: true
        class: OpenDxp\Resolver\ClassResolver
        arguments:
            $map: '%opendxp.assets.classes.map%'
