_opendxp_service_robots_txt:
    path: /robots.txt
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\PublicServicesController::robotsTxtAction }

_opendxp_service_version_badge:
    path: /version-badge
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\PublicServicesController::versionAction }

_opendxp_service_common_files:
    path: /{filename}
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\PublicServicesController::commonFilesAction }
    requirements:
        filename: '(robots\.txt|crossdomain\.xml|favicon\.ico|browserconfig\.xml|wpad\.dat|\.crl)'

_opendxp_service_common_files_apple_touch_icon:
    path: /{filename}
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\PublicServicesController::commonFilesAction }
    requirements:
        filename: 'apple\-touch\-icon.*'

_opendxp_service_thumbnail:
    path: '{prefix}{type}-thumb__{assetId}__{thumbnailName}/{filename}'
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\PublicServicesController::thumbnailAction}
    requirements:
        prefix: '.*'
        type: 'video|image'
        assetId: '\d+'
        thumbnailName: '[a-zA-Z0-9_\-]+'
        filename: '.*'

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.php"

# auto loads routes from all bundles in config/opendxp/routing.yaml
_opendxp_bundle_auto:
    resource: .
    type: opendxp_bundle

opendxp_webdav:
    path: /asset/webdav{path}
    defaults: { _controller: OpenDxp\Bundle\CoreBundle\Controller\WebDavController::webdavAction }
    requirements:
        path: '.*'
