services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpenDxp\Bundle\ApplicationLoggerBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('OpenDxpApplicationLoggerBundle')"

    OpenDxp\Bundle\ApplicationLoggerBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    OpenDxp\Bundle\ApplicationLoggerBundle\Grid\LogGridQueryFactory: ~

    OpenDxp\Bundle\ApplicationLoggerBundle\GridExport\LogGridExportSource: ~

    #
    # APPLICATION LOGGER
    #

    # Monolog processors for the application logger. Autoconfigure is set to false as we don't
    # want Symfony to auto-register them for all handlers (this isn't the case at the moment as
    # there is no interface for a processor, but in case support for autoconfiguration is added
    # we want to keep those processors only for the application logger.

    # ApplicationLoggerProcessor prepares data for the DB handler. This basically
    # mimics functionality from the ApplicationLogger itself to be used from any
    # monolog handler.
    OpenDxp\Bundle\ApplicationLoggerBundle\Processor\ApplicationLoggerProcessor: ~

    # IntrospectionProcessor adds data regarding called function/line. The skipClassesPartials makes sure
    # we skip the stack frame when called through ApplicationLogger.
    opendxp.app_logger.introspection_processor:
        class: Monolog\Processor\IntrospectionProcessor
        autoconfigure: false
        arguments:
            $level: 'DEBUG'
            $skipClassesPartials:
                - 'OpenDxp\Bundle\ApplicationLoggerBundle\ApplicationLogger'

    # the DB write handler
    OpenDxp\Bundle\ApplicationLoggerBundle\Handler\ApplicationLoggerDb:
        public: true
        calls:
            - [ pushProcessor, [ '@monolog.processor.psr_log_message' ] ]
            - [ pushProcessor, [ '@OpenDxp\Bundle\ApplicationLoggerBundle\Processor\ApplicationLoggerProcessor' ] ]
            - [ pushProcessor, [ '@opendxp.app_logger.introspection_processor' ] ]

    OpenDxp\Bundle\ApplicationLoggerBundle\ApplicationLogger:
        public: true
        calls:
            - [ addWriter, [ '@OpenDxp\Bundle\ApplicationLoggerBundle\Handler\ApplicationLoggerDb' ] ]

    OpenDxp\Log\ApplicationLogger:
        public: true
        alias: OpenDxp\Bundle\ApplicationLoggerBundle\ApplicationLogger

    opendxp.app_logger:
        public: true
        alias: opendxp.app_logger.default

    opendxp.app_logger.default:
        public: true
        alias: OpenDxp\Bundle\ApplicationLoggerBundle\ApplicationLogger

    OpenDxp\Bundle\ApplicationLoggerBundle\Maintenance\LogArchiveTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: opendxp.maintenance.task, type: archiveLogEntries }

    OpenDxp\Bundle\ApplicationLoggerBundle\Maintenance\LogMailMaintenanceTask:
        arguments:
            - '@doctrine.dbal.default_connection'
        tags:
            - { name: opendxp.maintenance.task, type: logmaintenance }